export const ALL_CATEGORIES_REQUEST = 'ALL_CATEGORIES_REQUEST';
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS';
export const ALL_CATEGORIES_FAIL = 'ALL_CATEGORIES_FAIL';

export const ALL_SUBCATEGORIES_REQUEST = 'ALL_SUBCATEGORIES_REQUEST';
export const ALL_SUBCATEGORIES_SUCCESS = 'ALL_SUBCATEGORIES_SUCCESS';
export const ALL_SUBCATEGORIES_FAIL = 'ALL_SUBCATEGORIES_FAIL';



export const CLEAR_ERRORS = 'CLEAR_ERRORS';