export const INITIALIZE_TRANSACTION = 'INITIALIZE_TRANSACTION'
export const INITIALIZE_TRANSACTION_SUCCESS = 'INITIALIZE_TRANSACTION_SUCESS'
export const INITIALIZE_TRANSACTION_FAIL = 'INITIALIZE_TRANSACTION_FAIL';

export const VERIFY_TRANSACTION = 'VERIFY_TRANSACTION';
export const VERIFY_TRANSACTION_SUCCESS = 'VERIFY_TRANSACTION_SUCCESS';
export const VERIFY_TRANSACTION_FAIL = 'VERIFY_TRANSACTION_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'